### ISSUE TITLE
Incompatible with latest version of google-cloud-pubsub

### ISSUE THREAD

**Issue by aaronkrolik** [ursm/activejob-google_cloud_pubsub#2]
Hi,
There is a small incompatibility that causes the activejob-google_cloud_pubsub-worker daemon to fail when using with google-cloud-pubsub 0.27.0. Line 10 in pubsub_extension.rb (https://github.com/ursm/activejob-google_cloud_pubsub/blob/96f841dbf9a674365fe13fbabb9d4ece98388fcf/lib/activejob-google_cloud_pubsub/pubsub_extension.rb#L10) initializes a topic with the `autocreate: true` argument. That argument was removed in the latest release:
https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/c4ada6f89efd7239bdd78305038b43d046f1f53b/google-cloud-pubsub/CHANGELOG.md

I'm happy to issue a pr if you would like.

**Comment by ursm** [comment]
Hello!
Thank you for telling me. I did not know that. I'm very happy if you can pull requests.
