### ISSUE TITLE
CI is not setup/readiness for production?

### ISSUE THREAD

**Issue by rosskevin** [ursm/activejob-google_cloud_pubsub#3]
I'm actively looking at a move to Googe PubSub.   I noticed travis is not setup:
https://travis-ci.org/ursm/activejob-google_cloud_pubsub

Is this gem being used in production?

If so, any current problems (such as latency or other)?

Thank you!

**Comment by ursm** [comment]
Hello, Thank you for your interest in this project. I think Travis CI is set up, so can you check it again?
I have created this gem to run the Rails application on the Google Cloud Platform, but I have never worked on a production environment yet. Therefore, there is a possibility that some problems may occur in the real environment.
